# Generated by Django 5.1.1 on 2024-09-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name_plural': 'Sections'},
        ),
    ]
