# Generated by Django 5.1.1 on 2024-09-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlist',
            name='lessons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchedlist',
            name='sections',
            field=models.IntegerField(),
        ),
    ]
